# Shared baremetal build logic for Raspberry Pi microcontrollers.
# Not included directly — sourced by a chip-specific file (rp2040.cmake,
# rp2350.cmake, ...) which sets the PICOFUSE_* variables below first.
#
# Required variables (set by chip file before including this):
#   PICOFUSE_ARMGNU      - toolchain prefix, e.g. arm-none-eabi
#   PICOFUSE_CPU         - compiler CPU name, e.g. cortex-m0plus
#   PICOFUSE_CHIP_DIR    - pico-sdk chip subdir, e.g. rp2040 or rp2350
#   PICOFUSE_FAMILY      - picotool family flag, e.g. rp2040 or rp2350
#   PICOFUSE_SRAM_ENTRY  - entry point for SRAM execution
#   PICOFUSE_SRAM_LOAD   - UF2 load address for SRAM execution
#   PICOFUSE_FLASH_ENTRY - entry point for flash execution
#   PICOFUSE_FLASH_LOAD  - UF2 load address for flash execution (0x10000000)

set(PICO_SDK_DIR "${CMAKE_CURRENT_LIST_DIR}/../third_party/pico-sdk"
    CACHE PATH "Path to pico-sdk submodule")

set(_PICOFUSE_BS2_DIR "${PICO_SDK_DIR}/src/${PICOFUSE_CHIP_DIR}/boot_stage2")

find_program(PICOFUSE_AS      ${PICOFUSE_ARMGNU}-as      REQUIRED)
find_program(PICOFUSE_GCC     ${PICOFUSE_ARMGNU}-gcc     REQUIRED)
find_program(PICOFUSE_LD      ${PICOFUSE_ARMGNU}-gcc     REQUIRED)
find_program(PICOFUSE_OBJDUMP ${PICOFUSE_ARMGNU}-objdump REQUIRED)
find_program(PICOFUSE_OBJCOPY ${PICOFUSE_ARMGNU}-objcopy REQUIRED)
find_program(PICOFUSE_PICOTOOL picotool
    PATHS /usr/local/bin $ENV{HOME}/pico/picotool/build
    REQUIRED
)
find_package(Python3 REQUIRED COMPONENTS Interpreter)

set(_PICOFUSE_AFLAGS  --warn --fatal-warnings -mcpu=${PICOFUSE_CPU} -g)
set(_PICOFUSE_CFLAGS  -mcpu=${PICOFUSE_CPU} -mthumb -nostartfiles -ffreestanding -g -O0
    -I${CMAKE_SOURCE_DIR}/include
    -I${PICO_SDK_DIR}/src/${PICOFUSE_CHIP_DIR}/hardware_regs/include)
if(DEFINED PICOFUSE_LED_PIN)
    list(APPEND _PICOFUSE_CFLAGS -DLED_PIN=${PICOFUSE_LED_PIN})
endif()
if(DEFINED PICOFUSE_USER_SW_PIN)
    list(APPEND _PICOFUSE_CFLAGS -DUSER_SW_PIN=${PICOFUSE_USER_SW_PIN})
endif()
if(DEFINED PICOFUSE_XOSC_HZ)
    list(APPEND _PICOFUSE_CFLAGS -DPICOFUSE_XOSC_HZ=${PICOFUSE_XOSC_HZ})
endif()
if(DEFINED PICOFUSE_SYS_CLK_HZ)
    list(APPEND _PICOFUSE_CFLAGS -DPICOFUSE_SYS_CLK_HZ=${PICOFUSE_SYS_CLK_HZ})
endif()
if(DEFINED PICOFUSE_IO_BANK0_IRQ)
    list(APPEND _PICOFUSE_CFLAGS -DPICOFUSE_IO_BANK0_IRQ=${PICOFUSE_IO_BANK0_IRQ})
endif()
if(DEFINED PICOFUSE_NUM_GPIOS)
    list(APPEND _PICOFUSE_CFLAGS -DPICOFUSE_NUM_GPIOS=${PICOFUSE_NUM_GPIOS})
endif()
set(_PICOFUSE_LDFLAGS -mcpu=${PICOFUSE_CPU} -mthumb -nostdlib)

# Internal: compile + pad + CRC32 a boot stage 2 source from the SDK.
# Produces a .o with a .boot2 section (256 bytes, CRC32 in last 4 bytes).
# Sets ${OUTPUT_VAR} in the caller's scope to the path of that object file.
function(_picofuse_build_boot2 BOOT2_NAME OUTPUT_VAR)
    set(_SRC  "${_PICOFUSE_BS2_DIR}/${BOOT2_NAME}.S")
    set(_DIR  "${CMAKE_CURRENT_BINARY_DIR}/boot2")
    set(_ELF  "${_DIR}/${BOOT2_NAME}.elf")
    set(_BIN  "${_DIR}/${BOOT2_NAME}.bin")
    set(_CS_S "${_DIR}/${BOOT2_NAME}_cs.S")
    set(_OBJ  "${_DIR}/${BOOT2_NAME}_cs.o")

    if(NOT EXISTS "${_SRC}")
        message(FATAL_ERROR "Boot stage 2 source not found: ${_SRC}")
    endif()

    # GCC with -x assembler-with-cpp handles #include / #define in the .S.
    # Our src/rp2040/include stub replaces pico/asm_helper.S to avoid pulling
    # in pico/config_autogen.h which is only generated by a full SDK build.
    add_custom_command(
        OUTPUT  "${_ELF}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${_DIR}"
        COMMAND ${PICOFUSE_GCC}
                -mcpu=${PICOFUSE_CPU} -mthumb
                -x assembler-with-cpp
                -I "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../include"
                -I "${_PICOFUSE_BS2_DIR}/asminclude"
                -I "${_PICOFUSE_BS2_DIR}/include"
                -I "${PICO_SDK_DIR}/src/${PICOFUSE_CHIP_DIR}/hardware_regs/include"
                -I "${PICO_SDK_DIR}/src/${PICOFUSE_CHIP_DIR}/pico_platform/include"
                -nostartfiles
                -T "${_PICOFUSE_BS2_DIR}/boot_stage2.ld"
                "${_SRC}" -o "${_ELF}"
        DEPENDS "${_SRC}"
        COMMENT "BS2 compile ${BOOT2_NAME}.elf"
    )

    add_custom_command(
        OUTPUT  "${_BIN}"
        COMMAND ${PICOFUSE_OBJCOPY} -O binary "${_ELF}" "${_BIN}"
        DEPENDS "${_ELF}"
        COMMENT "BS2 extract ${BOOT2_NAME}.bin"
    )

    # Pads to 256 bytes and appends the CRC32 the ROM verifies at boot
    add_custom_command(
        OUTPUT  "${_CS_S}"
        COMMAND ${Python3_EXECUTABLE}
                "${_PICOFUSE_BS2_DIR}/pad_checksum"
                -s 0xffffffff "${_BIN}" "${_CS_S}"
        DEPENDS "${_BIN}"
        COMMENT "BS2 pad+checksum ${BOOT2_NAME}_cs.S"
    )

    add_custom_command(
        OUTPUT  "${_OBJ}"
        COMMAND ${PICOFUSE_AS} ${_PICOFUSE_AFLAGS} "${_CS_S}" -o "${_OBJ}"
        DEPENDS "${_CS_S}"
        COMMENT "BS2 assemble ${BOOT2_NAME}_cs.o"
    )

    set(${OUTPUT_VAR} "${_OBJ}" PARENT_SCOPE)
endfunction()

# picofuse_add_executable(
#     NAME     <target>
#     C        <file.c> ...          # at least one C source required
#     LDSCRIPT <linker-script.ld>   # relative path; falls back to PICOFUSE_LDSCRIPT
#     BOOT2    <sdk-boot2-name>     # falls back to PICOFUSE_BOOT2
#     ASM      <file.s> ...         # additional assembly; PICOFUSE_STARTUP always prepended
# )
function(picofuse_add_executable)
    cmake_parse_arguments(_ARG "" "NAME;LDSCRIPT;BOOT2" "ASM;C" ${ARGN})

    if(NOT _ARG_NAME)
        message(FATAL_ERROR "picofuse_add_executable: NAME is required")
    endif()
    if(NOT _ARG_C AND NOT _ARG_ASM)
        message(FATAL_ERROR "picofuse_add_executable: at least one C or ASM source is required")
    endif()

    # LDSCRIPT: explicit (relative to caller) > board default (absolute)
    if(_ARG_LDSCRIPT)
        set(_LDSCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/${_ARG_LDSCRIPT})
    elseif(DEFINED PICOFUSE_LDSCRIPT)
        set(_LDSCRIPT ${PICOFUSE_LDSCRIPT})
    else()
        message(FATAL_ERROR "picofuse_add_executable: LDSCRIPT is required (or set PICOFUSE_LDSCRIPT in board cmake)")
    endif()

    # BOOT2: explicit > board default
    if(NOT _ARG_BOOT2 AND DEFINED PICOFUSE_BOOT2)
        set(_ARG_BOOT2 ${PICOFUSE_BOOT2})
    endif()

    set(_NAME    ${_ARG_NAME})
    set(_OBJECTS)

    # Boot stage 2 object goes first so it lands at 0x10000000 in flash
    if(_ARG_BOOT2)
        _picofuse_build_boot2(${_ARG_BOOT2} _BOOT2_OBJ)
        list(APPEND _OBJECTS "${_BOOT2_OBJ}")
        set(_ENTRY     ${PICOFUSE_FLASH_ENTRY})
        set(_LOAD_ADDR ${PICOFUSE_FLASH_LOAD})
    else()
        set(_ENTRY     ${PICOFUSE_SRAM_ENTRY})
        set(_LOAD_ADDR ${PICOFUSE_SRAM_LOAD})
    endif()

    # Board startup always goes first (absolute path from board cmake)
    if(DEFINED PICOFUSE_STARTUP)
        get_filename_component(_BASE ${PICOFUSE_STARTUP} NAME_WE)
        set(_OBJ ${CMAKE_CURRENT_BINARY_DIR}/${_BASE}.o)
        add_custom_command(
            OUTPUT  ${_OBJ}
            COMMAND ${PICOFUSE_AS} ${_PICOFUSE_AFLAGS} ${PICOFUSE_STARTUP} -o ${_OBJ}
            DEPENDS ${PICOFUSE_STARTUP}
            COMMENT "AS (startup) ${_BASE}.s"
        )
        list(APPEND _OBJECTS ${_OBJ})
    endif()

    foreach(_SRC ${_ARG_ASM})
        get_filename_component(_BASE ${_SRC} NAME_WE)
        set(_OBJ ${CMAKE_CURRENT_BINARY_DIR}/${_BASE}.o)
        add_custom_command(
            OUTPUT  ${_OBJ}
            COMMAND ${PICOFUSE_AS} ${_PICOFUSE_AFLAGS}
                    ${CMAKE_CURRENT_SOURCE_DIR}/${_SRC} -o ${_OBJ}
            DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${_SRC}
            COMMENT "AS ${_SRC}"
        )
        list(APPEND _OBJECTS ${_OBJ})
    endforeach()

    # Chip-level sources (gpio.c etc.) from board's chip cmake
    foreach(_SRC ${PICOFUSE_CHIP_SOURCES})
        get_filename_component(_BASE ${_SRC} NAME_WE)
        set(_OBJ ${CMAKE_CURRENT_BINARY_DIR}/chip/${_BASE}.o)
        add_custom_command(
            OUTPUT  ${_OBJ}
            COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/chip"
            COMMAND ${PICOFUSE_GCC} ${_PICOFUSE_CFLAGS} -c ${_SRC} -o ${_OBJ}
            DEPENDS ${_SRC}
            COMMENT "CC (chip) ${_BASE}.c"
        )
        list(APPEND _OBJECTS ${_OBJ})
    endforeach()

    foreach(_SRC ${_ARG_C})
        get_filename_component(_BASE ${_SRC} NAME_WE)
        set(_OBJ ${CMAKE_CURRENT_BINARY_DIR}/${_BASE}.o)
        add_custom_command(
            OUTPUT  ${_OBJ}
            COMMAND ${PICOFUSE_GCC} ${_PICOFUSE_CFLAGS} -c
                    ${CMAKE_CURRENT_SOURCE_DIR}/${_SRC} -o ${_OBJ}
            DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${_SRC}
            COMMENT "CC ${_SRC}"
        )
        list(APPEND _OBJECTS ${_OBJ})
    endforeach()

    set(_ELF  ${CMAKE_CURRENT_BINARY_DIR}/${_NAME}.elf)
    set(_LIST ${CMAKE_CURRENT_BINARY_DIR}/${_NAME}.list)
    set(_BIN  ${CMAKE_CURRENT_BINARY_DIR}/${_NAME}.bin)
    set(_UF2  ${CMAKE_CURRENT_BINARY_DIR}/${_NAME}.uf2)

    add_custom_command(
        OUTPUT  ${_ELF}
        COMMAND ${PICOFUSE_LD} ${_PICOFUSE_LDFLAGS}
                -Wl,--entry=${_ENTRY} -T ${_LDSCRIPT}
                ${_OBJECTS} -lgcc -o ${_ELF}
        DEPENDS ${_OBJECTS} ${_LDSCRIPT}
        COMMENT "LD ${_NAME}.elf"
    )

    add_custom_command(
        OUTPUT  ${_LIST}
        COMMAND ${PICOFUSE_OBJDUMP} -D ${_ELF} > ${_LIST}
        DEPENDS ${_ELF}
        COMMENT "OBJDUMP ${_NAME}.list"
    )

    add_custom_command(
        OUTPUT  ${_BIN}
        COMMAND ${PICOFUSE_OBJCOPY} -O binary ${_ELF} ${_BIN}
        DEPENDS ${_ELF}
        COMMENT "OBJCOPY ${_NAME}.bin"
    )

    add_custom_command(
        OUTPUT  ${_UF2}
        COMMAND ${PICOFUSE_PICOTOOL} uf2 convert ${_BIN} ${_UF2}
                -o ${_LOAD_ADDR} --family ${PICOFUSE_FAMILY}
        DEPENDS ${_BIN}
        COMMENT "UF2 ${_NAME}.uf2"
    )

    add_custom_target(${_NAME} ALL DEPENDS ${_UF2} ${_LIST})
endfunction()
