#include <picofuse/hid/keycode.h>
#include <picofuse/sys.h>
#include <stddef.h>

// This whole symbolic lookup collapses to nothing in release builds -
// hid_keycode_to_string() falls straight through to the hex fallback
// below when NDEBUG is defined, so none of this table gets compiled in.
#ifndef NDEBUG
#define HID_KEYCODE_CASE(name)                                                \
  case name:                                                                  \
    return #name;

static const char *_hid_keycode_name(uint16_t keycode) {
  switch (keycode) {
    HID_KEYCODE_CASE(KEYCODE_NONE)
    HID_KEYCODE_CASE(KEYCODE_ESC)
    HID_KEYCODE_CASE(KEYCODE_1)
    HID_KEYCODE_CASE(KEYCODE_2)
    HID_KEYCODE_CASE(KEYCODE_3)
    HID_KEYCODE_CASE(KEYCODE_4)
    HID_KEYCODE_CASE(KEYCODE_5)
    HID_KEYCODE_CASE(KEYCODE_6)
    HID_KEYCODE_CASE(KEYCODE_7)
    HID_KEYCODE_CASE(KEYCODE_8)
    HID_KEYCODE_CASE(KEYCODE_9)
    HID_KEYCODE_CASE(KEYCODE_0)
    HID_KEYCODE_CASE(KEYCODE_MINUS)
    HID_KEYCODE_CASE(KEYCODE_EQUAL)
    HID_KEYCODE_CASE(KEYCODE_BACKSPACE)
    HID_KEYCODE_CASE(KEYCODE_TAB)
    HID_KEYCODE_CASE(KEYCODE_Q)
    HID_KEYCODE_CASE(KEYCODE_W)
    HID_KEYCODE_CASE(KEYCODE_E)
    HID_KEYCODE_CASE(KEYCODE_R)
    HID_KEYCODE_CASE(KEYCODE_T)
    HID_KEYCODE_CASE(KEYCODE_Y)
    HID_KEYCODE_CASE(KEYCODE_U)
    HID_KEYCODE_CASE(KEYCODE_I)
    HID_KEYCODE_CASE(KEYCODE_O)
    HID_KEYCODE_CASE(KEYCODE_P)
    HID_KEYCODE_CASE(KEYCODE_LEFTBRACE)
    HID_KEYCODE_CASE(KEYCODE_RIGHTBRACE)
    HID_KEYCODE_CASE(KEYCODE_ENTER)
    HID_KEYCODE_CASE(KEYCODE_LEFTCTRL)
    HID_KEYCODE_CASE(KEYCODE_A)
    HID_KEYCODE_CASE(KEYCODE_S)
    HID_KEYCODE_CASE(KEYCODE_D)
    HID_KEYCODE_CASE(KEYCODE_F)
    HID_KEYCODE_CASE(KEYCODE_G)
    HID_KEYCODE_CASE(KEYCODE_H)
    HID_KEYCODE_CASE(KEYCODE_J)
    HID_KEYCODE_CASE(KEYCODE_K)
    HID_KEYCODE_CASE(KEYCODE_L)
    HID_KEYCODE_CASE(KEYCODE_SEMICOLON)
    HID_KEYCODE_CASE(KEYCODE_APOSTROPHE)
    HID_KEYCODE_CASE(KEYCODE_GRAVE)
    HID_KEYCODE_CASE(KEYCODE_LEFTSHIFT)
    HID_KEYCODE_CASE(KEYCODE_BACKSLASH)
    HID_KEYCODE_CASE(KEYCODE_Z)
    HID_KEYCODE_CASE(KEYCODE_X)
    HID_KEYCODE_CASE(KEYCODE_C)
    HID_KEYCODE_CASE(KEYCODE_V)
    HID_KEYCODE_CASE(KEYCODE_B)
    HID_KEYCODE_CASE(KEYCODE_N)
    HID_KEYCODE_CASE(KEYCODE_M)
    HID_KEYCODE_CASE(KEYCODE_COMMA)
    HID_KEYCODE_CASE(KEYCODE_DOT)
    HID_KEYCODE_CASE(KEYCODE_SLASH)
    HID_KEYCODE_CASE(KEYCODE_RIGHTSHIFT)
    HID_KEYCODE_CASE(KEYCODE_KPASTERISK)
    HID_KEYCODE_CASE(KEYCODE_LEFTALT)
    HID_KEYCODE_CASE(KEYCODE_SPACE)
    HID_KEYCODE_CASE(KEYCODE_CAPSLOCK)
    HID_KEYCODE_CASE(KEYCODE_F1)
    HID_KEYCODE_CASE(KEYCODE_F2)
    HID_KEYCODE_CASE(KEYCODE_F3)
    HID_KEYCODE_CASE(KEYCODE_F4)
    HID_KEYCODE_CASE(KEYCODE_F5)
    HID_KEYCODE_CASE(KEYCODE_F6)
    HID_KEYCODE_CASE(KEYCODE_F7)
    HID_KEYCODE_CASE(KEYCODE_F8)
    HID_KEYCODE_CASE(KEYCODE_F9)
    HID_KEYCODE_CASE(KEYCODE_F10)
    HID_KEYCODE_CASE(KEYCODE_NUMLOCK)
    HID_KEYCODE_CASE(KEYCODE_SCROLLLOCK)
    HID_KEYCODE_CASE(KEYCODE_KP7)
    HID_KEYCODE_CASE(KEYCODE_KP8)
    HID_KEYCODE_CASE(KEYCODE_KP9)
    HID_KEYCODE_CASE(KEYCODE_KPMINUS)
    HID_KEYCODE_CASE(KEYCODE_KP4)
    HID_KEYCODE_CASE(KEYCODE_KP5)
    HID_KEYCODE_CASE(KEYCODE_KP6)
    HID_KEYCODE_CASE(KEYCODE_KPPLUS)
    HID_KEYCODE_CASE(KEYCODE_KP1)
    HID_KEYCODE_CASE(KEYCODE_KP2)
    HID_KEYCODE_CASE(KEYCODE_KP3)
    HID_KEYCODE_CASE(KEYCODE_KP0)
    HID_KEYCODE_CASE(KEYCODE_KPDOT)
    HID_KEYCODE_CASE(KEYCODE_F11)
    HID_KEYCODE_CASE(KEYCODE_F12)
    HID_KEYCODE_CASE(KEYCODE_KPENTER)
    HID_KEYCODE_CASE(KEYCODE_RIGHTCTRL)
    HID_KEYCODE_CASE(KEYCODE_KPSLASH)
    HID_KEYCODE_CASE(KEYCODE_SYSRQ)
    HID_KEYCODE_CASE(KEYCODE_RIGHTALT)
    HID_KEYCODE_CASE(KEYCODE_LINEFEED)
    HID_KEYCODE_CASE(KEYCODE_HOME)
    HID_KEYCODE_CASE(KEYCODE_UP)
    HID_KEYCODE_CASE(KEYCODE_PAGEUP)
    HID_KEYCODE_CASE(KEYCODE_LEFT)
    HID_KEYCODE_CASE(KEYCODE_RIGHT)
    HID_KEYCODE_CASE(KEYCODE_END)
    HID_KEYCODE_CASE(KEYCODE_DOWN)
    HID_KEYCODE_CASE(KEYCODE_PAGEDOWN)
    HID_KEYCODE_CASE(KEYCODE_INSERT)
    HID_KEYCODE_CASE(KEYCODE_DELETE)
    HID_KEYCODE_CASE(KEYCODE_MACRO)
    HID_KEYCODE_CASE(KEYCODE_MUTE)
    HID_KEYCODE_CASE(KEYCODE_VOLUMEDOWN)
    HID_KEYCODE_CASE(KEYCODE_VOLUMEUP)
    HID_KEYCODE_CASE(KEYCODE_POWER)
    HID_KEYCODE_CASE(KEYCODE_KPEQUAL)
    HID_KEYCODE_CASE(KEYCODE_KPPLUSMINUS)
    HID_KEYCODE_CASE(KEYCODE_KPCOMMA)
    HID_KEYCODE_CASE(KEYCODE_LEFTMETA)
    HID_KEYCODE_CASE(KEYCODE_RIGHTMETA)
    HID_KEYCODE_CASE(KEYCODE_SLEEP)
    HID_KEYCODE_CASE(KEYCODE_WAKEUP)
    HID_KEYCODE_CASE(KEYCODE_KPLEFTPAREN)
    HID_KEYCODE_CASE(KEYCODE_KPRIGHTPAREN)
    HID_KEYCODE_CASE(KEYCODE_F13)
    HID_KEYCODE_CASE(KEYCODE_F14)
    HID_KEYCODE_CASE(KEYCODE_F15)
    HID_KEYCODE_CASE(KEYCODE_F16)
    HID_KEYCODE_CASE(KEYCODE_F17)
    HID_KEYCODE_CASE(KEYCODE_F18)
    HID_KEYCODE_CASE(KEYCODE_F19)
    HID_KEYCODE_CASE(KEYCODE_F20)
    HID_KEYCODE_CASE(KEYCODE_F21)
    HID_KEYCODE_CASE(KEYCODE_F22)
    HID_KEYCODE_CASE(KEYCODE_F23)
    HID_KEYCODE_CASE(KEYCODE_F24)
    HID_KEYCODE_CASE(KEYCODE_CLOSE)
    HID_KEYCODE_CASE(KEYCODE_PLAY)
    HID_KEYCODE_CASE(KEYCODE_PRINT)
    HID_KEYCODE_CASE(KEYCODE_SEARCH)
    HID_KEYCODE_CASE(KEYCODE_CANCEL)
    HID_KEYCODE_CASE(KEYCODE_BRIGHTNESS_DOWN)
    HID_KEYCODE_CASE(KEYCODE_BRIGHTNESS_UP)
    HID_KEYCODE_CASE(KEYCODE_BRIGHTNESS_CYCLE)
    HID_KEYCODE_CASE(KEYCODE_BRIGHTNESS_AUTO)
    HID_KEYCODE_CASE(KEYCODE_BTN0)
    HID_KEYCODE_CASE(KEYCODE_BTN1)
    HID_KEYCODE_CASE(KEYCODE_BTN2)
    HID_KEYCODE_CASE(KEYCODE_BTN3)
    HID_KEYCODE_CASE(KEYCODE_BTN4)
    HID_KEYCODE_CASE(KEYCODE_BTN5)
    HID_KEYCODE_CASE(KEYCODE_BTN6)
    HID_KEYCODE_CASE(KEYCODE_BTN7)
    HID_KEYCODE_CASE(KEYCODE_BTN8)
    HID_KEYCODE_CASE(KEYCODE_BTN9)
    HID_KEYCODE_CASE(KEYCODE_BTNLEFT)
    HID_KEYCODE_CASE(KEYCODE_BTNRIGHT)
    HID_KEYCODE_CASE(KEYCODE_BTNMIDDLE)
    HID_KEYCODE_CASE(KEYCODE_BTNSIDE)
    HID_KEYCODE_CASE(KEYCODE_BTNEXTRA)
    HID_KEYCODE_CASE(KEYCODE_BTNTOUCH)
    HID_KEYCODE_CASE(KEYCODE_EJECT)
    HID_KEYCODE_CASE(KEYCODE_POWER_OFF)
    HID_KEYCODE_CASE(KEYCODE_POWER_ON)
    HID_KEYCODE_CASE(KEYCODE_INPUT_SELECT)
    HID_KEYCODE_CASE(KEYCODE_INPUT_PC)
    HID_KEYCODE_CASE(KEYCODE_INPUT_VIDEO1)
    HID_KEYCODE_CASE(KEYCODE_INPUT_VIDEO2)
    HID_KEYCODE_CASE(KEYCODE_INPUT_VIDEO3)
    HID_KEYCODE_CASE(KEYCODE_INPUT_VIDEO4)
    HID_KEYCODE_CASE(KEYCODE_INPUT_VIDEO5)
    HID_KEYCODE_CASE(KEYCODE_INPUT_HDMI1)
    HID_KEYCODE_CASE(KEYCODE_INPUT_HDMI2)
    HID_KEYCODE_CASE(KEYCODE_INPUT_HDMI3)
    HID_KEYCODE_CASE(KEYCODE_INPUT_HDMI4)
    HID_KEYCODE_CASE(KEYCODE_INPUT_HDMI5)
    HID_KEYCODE_CASE(KEYCODE_INPUT_AUX1)
    HID_KEYCODE_CASE(KEYCODE_INPUT_AUX2)
    HID_KEYCODE_CASE(KEYCODE_INPUT_AUX3)
    HID_KEYCODE_CASE(KEYCODE_INPUT_AUX4)
    HID_KEYCODE_CASE(KEYCODE_INPUT_AUX5)
    HID_KEYCODE_CASE(KEYCODE_INPUT_CD)
    HID_KEYCODE_CASE(KEYCODE_INPUT_DVD)
    HID_KEYCODE_CASE(KEYCODE_INPUT_PHONO)
    HID_KEYCODE_CASE(KEYCODE_INPUT_TAPE1)
    HID_KEYCODE_CASE(KEYCODE_INPUT_TAPE2)
    HID_KEYCODE_CASE(KEYCODE_INPUT_TUNER)
    HID_KEYCODE_CASE(KEYCODE_INPUT_ANALOG)
    HID_KEYCODE_CASE(KEYCODE_INPUT_DIGITAL)
    HID_KEYCODE_CASE(KEYCODE_INPUT_INTERNET)
    HID_KEYCODE_CASE(KEYCODE_INPUT_TEXT)
    HID_KEYCODE_CASE(KEYCODE_INPUT_NEXT)
    HID_KEYCODE_CASE(KEYCODE_INPUT_PREV)
    HID_KEYCODE_CASE(KEYCODE_VIDEO_ASPECT)
    HID_KEYCODE_CASE(KEYCODE_VIDEO_PIP)
    HID_KEYCODE_CASE(KEYCODE_AUDIO_MONITOR)
    HID_KEYCODE_CASE(KEYCODE_CLEAR)
    HID_KEYCODE_CASE(KEYCODE_TIMER)
    HID_KEYCODE_CASE(KEYCODE_CHANNEL_PREV)
    HID_KEYCODE_CASE(KEYCODE_CHANNEL_GUIDE)
    HID_KEYCODE_CASE(KEYCODE_RECORD)
    HID_KEYCODE_CASE(KEYCODE_RECORD_SPEED)
    HID_KEYCODE_CASE(KEYCODE_PLAY_SPEED)
    HID_KEYCODE_CASE(KEYCODE_PLAY_MODE)
    HID_KEYCODE_CASE(KEYCODE_REPLAY)
    HID_KEYCODE_CASE(KEYCODE_DISPLAY)
    HID_KEYCODE_CASE(KEYCODE_MENU)
    HID_KEYCODE_CASE(KEYCODE_INFO)
    HID_KEYCODE_CASE(KEYCODE_THUMBS_UP)
    HID_KEYCODE_CASE(KEYCODE_THUMBS_DOWN)
    HID_KEYCODE_CASE(KEYCODE_FAVOURITE)
    HID_KEYCODE_CASE(KEYCODE_BUTTON_RED)
    HID_KEYCODE_CASE(KEYCODE_BUTTON_GREEN)
    HID_KEYCODE_CASE(KEYCODE_BUTTON_YELLOW)
    HID_KEYCODE_CASE(KEYCODE_BUTTON_BLUE)
    HID_KEYCODE_CASE(KEYCODE_SEARCH_LEFT)
    HID_KEYCODE_CASE(KEYCODE_SEARCH_RIGHT)
    HID_KEYCODE_CASE(KEYCODE_CHAPTER_NEXT)
    HID_KEYCODE_CASE(KEYCODE_CHAPTER_PREV)
    HID_KEYCODE_CASE(KEYCODE_NAV_SELECT)
    HID_KEYCODE_CASE(KEYCODE_SUBTITLE_TOGGLE)
    HID_KEYCODE_CASE(KEYCODE_SUBTITLE_ON)
    HID_KEYCODE_CASE(KEYCODE_SUBTITLE_OFF)
    HID_KEYCODE_CASE(KEYCODE_STOP)
    HID_KEYCODE_CASE(KEYCODE_PAUSE)
    HID_KEYCODE_CASE(KEYCODE_BROWSE)
    HID_KEYCODE_CASE(KEYCODE_SHUFFLE)
    HID_KEYCODE_CASE(KEYCODE_REPEAT)
    HID_KEYCODE_CASE(KEYCODE_KEYPAD_10PLUS)
    HID_KEYCODE_CASE(KEYCODE_BUTTON_USER)
  default:
    return NULL;
  }
}
#endif

const char *hid_keycode_to_string(uint16_t keycode) {
#ifndef NDEBUG
  const char *name = _hid_keycode_name(keycode);
  if (name != NULL) {
    return name;
  }
#endif
  static char buf[8];
  sys_sprintf(buf, sizeof(buf), "0x%04X", keycode);
  return buf;
}

size_t hid_state_to_string(hid_state_t state, char *buf, size_t buf_size) {
  static const struct {
    hid_state_t flag;
    const char *name;
  } flags[] = {
      {hid_state_on, "on"},
      {hid_state_off, "off"},
      {hid_state_click, "click"},
      {hid_state_double_click, "double_click"},
      {hid_state_triple_click, "triple_click"},
      {hid_state_long_click, "long_click"},
      {hid_state_repeat, "repeat"},
      {hid_state_function, "function"},
      {hid_state_caps_lock, "caps_lock"},
      {hid_state_num_lock, "num_lock"},
      {hid_state_scroll_lock, "scroll_lock"},
      {hid_state_left_shift, "left_shift"},
      {hid_state_right_shift, "right_shift"},
      {hid_state_left_meta, "left_meta"},
      {hid_state_right_meta, "right_meta"},
      {hid_state_left_alt, "left_alt"},
      {hid_state_right_alt, "right_alt"},
      {hid_state_left_control, "left_control"},
      {hid_state_right_control, "right_control"},
      {hid_state_left_windows, "left_windows"},
      {hid_state_right_windows, "right_windows"},
  };

  if (buf == NULL || buf_size == 0) {
    return 0;
  }

  size_t offset = 0;
  bool any = false;

  for (size_t i = 0; i < sizeof(flags) / sizeof(flags[0]); i++) {
    if ((state & flags[i].flag) == 0) {
      continue;
    }
    if (offset >= buf_size) {
      break;
    }
    offset += sys_sprintf(buf + offset, buf_size - offset, "%s%s",
                          any ? "|" : "", flags[i].name);
    any = true;
  }

  if (!any) {
    offset = sys_sprintf(buf, buf_size, "none");
  }

  return offset;
}
